name: Post TrueCast News

on:
  schedule:
    # Runs at 15:00 UTC every day (3 hours after market updates)
    - cron: '0 15 * * *'
  
  # Allows manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  post-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'  # Fetches all submodules recursively
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
      with:
        version: 10
        
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: "pnpm"
        cache-dependency-path: ./cdp-agentkit/typescript
        
    - name: Install and build cdp-agentkit
      run: |
        cd cdp-agentkit/typescript
        
        # Install dependencies for the monorepo
        pnpm i --frozen-lockfile && pnpm build
      
        cd ../..
        
    - name: Install myAgent dependencies
      run: |
        cd myAgent
        npm install
        
    - name: Run News Posting
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CDP_API_KEY_NAME: ${{ secrets.CDP_API_KEY_NAME }}
        CDP_API_KEY_PRIVATE_KEY: ${{ secrets.CDP_API_KEY_PRIVATE_KEY }}
        NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
        NETWORK_ID: ${{ secrets.NETWORK_ID }}
        RPC_URL: ${{ secrets.RPC_URL }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
        REDIS_TOKEN: ${{ secrets.REDIS_TOKEN }}
        NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME: ${{ secrets.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME }}
        PINATA_JWT: ${{ secrets.PINATA_JWT }}
        DISABLE_POSTS: ${{ secrets.DISABLE_POSTS }}
        MAX_NEWS_POSTS: ${{ vars.MAX_NEWS_POSTS }}
        BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
      run: |
        cd myAgent
        npm run post-news 